namespace SimGame.Domain
{
    public enum ProductTypeEnum
    {
        Metal           = 1,
        Wood            = 2,
        Plastic         = 3,
        Seed            = 4,
        Mineral         = 5,
        Chemical        = 6,
        Textiles        = 7,
        SugarAndSpice   = 8,
        Glass           = 9,
        Hammer          = 10,
        MeasuringTape   = 11,
        Shovel          = 12,
        KitchenUtensils = 13,
        Nail            = 14,
        Planks          = 15,
        Brick           = 16,
        Cement          = 17,
        Glue            = 18,
        Chair           = 19,
        Table           = 20,
        Grass           = 21,
        TreeSapling     = 22,
        LawnFurniture   = 23,
        Vegetable       = 24,
        Flour           = 25,
        FruitsAndBerries = 26,
        Cream           = 27,
        Donut           = 28,
        GreenSmoothie   = 29,
        Cap             = 30,
        Shoe            = 31,
        Watch           = 32,
        ElectricalComponent = 33,
        HomeTextiles    = 34,
        FirePit         = 35,
        Cheese          = 36,
        Beef            = 37,
        BreadRoll       = 38,
        CherryCheeseCake = 39,
        FrozenYogurt    = 40,
        Drill           = 41,
        AnimalFeed      = 42,
        IceCreamSandwich    = 43,
        Pizza           = 44,
        BBQGrill           = 45,
        Burger          = 46,
        BusinessSuit = 47,
        CheeseFries = 48,
        Refrigerator = 49,
        GardenGnome = 50,
        Couch = 51,
        LightingSystem = 52
    }
}